### PR TITLE
Adding test case to reproduce  issue 38

### PR DESCRIPTION
**Pull request by jliebrand**
NOTE: Still requires proper expected result, but until it works
I do not know what the expected result should be.
Also: can do with simplification of the input geojson.

### CODE REVIEW

**Comment by mfogel** [comment]
Awesome, thanks. This is helpful. If you get a chance to simplify the input geojson just update this PR

**Comment by mfogel** [comment]
Ok, I've simplified this failing test case some more. I still get a max call stack size exceeded error running a `union` on the following polygons:

```javascript
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-76.377, 38.782],
            [-76.385, 38.765],
            [-76.393, 38.758],
            [-76.343, 38.714],
            [-76.509, 38.751],
            [-76.377, 38.782]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-76.377, 38.749],
            [-76.388, 38.755],
            [-76.383, 38.756],
            [-76.377, 38.749]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-76.377, 38.782],
            [-76.339, 38.721],
            [-76.376, 38.742],
            [-76.377, 38.782]
          ]
        ]
      }
    }
  ]
}
```

which is pretty great, because so far this appears *not* to be a rounding/floating point issue.

**Comment by jliebrand** [comment]
Nice one!

**Comment by mfogel** [comment]
@jliebrand I cherry-picked your commits over to another branch, which I just merged into master. This will go out in a version 0.9 laster this evening.

**Comment by mfogel** [comment]
And - thanks much for the bug report and PR!

**Pull request closed without merging**
