### PR TITLE
Adding bounding box optimisation

### PR DESCRIPTION
**Pull request by rowanwins**
Hi @mfogel 

This pull request adds a bounding box optimisation for the intersect and difference operations, pretty much taken from the martinez repo.

The basic premise is that 
- as we're loop through each of the vertices initially use that to work out the bounding box of input geometries
- as we then work through the sweep line, for intersect and difference operations we can use that bbox information to stop unnecessary looping

From my quick look on the demo site this makes the intersection operation twice as fast on the asia demo.

Also FYI I'm getting some errors when I run the tests, they all seem to be along the lines of
````
    JSONError: Unexpected token 'u' at 1:1 in test\end-to-end\clean-poly-with-repeated-and-extra-points\intersection.geojson
    union.geojson
    ^
````
I'm guessing this might be a windows filepath type error, when I look at the file in github here I see they are supposed to be symbolic links between files...?

Anyway if you have any questions of suggestions let me know.

### CODE REVIEW

**Comment by mfogel** [comment]
@rowanwins great, thanks for the contribution

Running the tests - yeah there are symbolic links. I'm going to go ahead and change how that's designed so that there's no need for sym links there. I want people to be able to run the test suite early and often! :)

In general the optimization sounds good. I will come back around to this PR with any comments I have on the actual code over the weekend.

**Comment by mfogel** [comment]
I just dropped a commit on master that should fix the test suite issues. Let me know if it helps.

**Comment by mfogel** [comment]
Looking over the (18) failing tests on this branch it seems they fall into a few categories:

 * (2) `tests/clean-input.tests.js`: failing unit tests for `pointsAsObjects()`. This PR changes that function, so these tests need to be updated.
 * (1) `test/index.test.j` unit test for `doIt()`. This test validates `pointsAsObjects()` is called as excpected - this test needs to be updated
 * (5) `test/end-to-end-errors.test.js` exceptions no longer thrown for self-intersecting rings. These tests will likely be changed because of #30 - so I think for the purposes of this PR it's safe to ignore these failures and assume they will be delt with on #30.
 * (10) `test/end-to-end.test.js` 'clean' no longer works - ie. calling one of the top level functions of this lib with one argument in order to clean the input doesn't work. That's fine as detailed in my comment above, but we do need to make the changes listed it out in that comment. Effectively these failing tests will be removed.

There have been some changes on master since this PR was opened, although they *shouldn't* affect this branch it would probably be smart to either merge master into this branch or rebase this on the lastest on master.

**Comment by rowanwins** [comment]
Hey @mfogel 

Yeah I will get back to this hopefully in the next week or so :)  

I'm trying to put out an alpha of turf v7 in the next week or so which contains a dependency on this repo, I think it's a better match API-wise than the original `martinez` repo, While the v7 of turf it sits in alpha for a few months I'll turn my focus to trying to get some performance wins on this repo. There will be a number of breaking changes in Turf v7 hence why Im happy for it to sit in alpha for a while.

**Comment by mfogel** [comment]
Closing in favor of #55

**Pull request closed without merging**
